jh0ker/mau_mau_bot

locales/de_DE/LC_MESSAGES/unobot.po
locales/es_ES/LC_MESSAGES/unobot.po
locales/id_ID/LC_MESSAGES/unobot.po
locales/it_IT/LC_MESSAGES/unobot.po
locales/pt_BR/LC_MESSAGES/unobot.po

Small update in translations :D

Small update in translations

---

locales/pt_BR/LC_MESSAGES/unobot.po

Added plurals for  translation pt_BR :D

Update pt_BR (Add plurals)

---

bot.py

Feature : people run /next_game to get a pm from unobot when the next game starts in the group

added next_game , get a pm from  when next game starts

---

bot.py
credentials.py
locales/pt_BR/LC_MESSAGES/unobot.po
locales/unobot.pot

- ADD two new field for translation
- Update translation for PT_BR

Update and Fix Translation

---

locales/zh_TW/LC_MESSAGES/unobot.po

I found many translation mistakes in this translation and some of the new strings weren't translated ,and I have re-translated from English.

Zh-Tw Translatiion

---

shared_vars.py

telegram.utils.botan being deprecated change to telegram.contrib.botan

simple fix for botan

---

TRANSLATORS.md

Forgetting to add my name to translator team.

Add translater

---

AUTHORS.md
Pipfile
Pipfile.lock
TRANSLATORS.md
actions.py
genpot.sh
locales/unobot.pot
locales/zh_TW/LC_MESSAGES/unobot.po
simple_commands.py

- Updated / Improved Chinese (Taiwan) translations.
- author: @pan93412 and @jimchen5209 (former)
- Add pipenv support.
- Add pot update script and updated pot.

feature, l10n, i18n: Add pipenv support, let more strings translatable and some improves.

---

bot.py

Added "Make your choice!" button for start game message and next player message

Added an useful button

---

locales/compile.sh

Check for correct path in compile.sh

---

Dockerfile
shared_vars.py

Adds Dockerfile for easy selfhosting with docker.
When accepted I'll also add example docker-compose ;)

Basic docker support

---

README.md
commandlist.txt

Updated readme to include setting up command autocompletion via /setcommands and created a list of commands in commandlist.txt

Add commandlist.txt and update readme

---

test/test_player.py

Since deck is empty before the game is started so I add a game.start expression before drawing cards.

Fix DeckEmptyError

---

locales/pt_BR/LC_MESSAGES/unobot.po

Changed "jogo" to "partida" in the help command for consistency, made punctuation match original english texts, changed all "jogador" to "jogador(a)" for consistency, and minor changes

brazilian portuguese revision

---

Dockerfile

Changed the python version to supported by the telegram lib and bot 
Removed extra requirements.txt installation

Dockerfile changes :Changed the python version + removed extra requirements.txt

---

.github/workflows/docker-publish.yml

for this to work there's also a need to enable github actions in the project settings

feat(ci): build docker images on push and on the schedule

---

locales/available.py
locales/compile.sh
locales/hn_IN/LC_MESSAGES/unobot.po

Added Hindi Language 

---

config.py

checks for config.json if not available then uses vars from env

Config from environment

---

Dockerfile
requirements.txt

also bumps python-telegram-bot to latest known-compatible version

fix(Dockerfile): pin python version to 3.11

---

AUTHORS.md
config.py

- `ADMIN_LIST` from env vars were not parsed (expected list, os.getenv returns a str)
- Removed incorrect condition check for `OPEN_LOBBY` and `ENABLE_TRANSLATIONS` (bool from json was compared to str)

Improve admin list and bool parsing from envvars
